//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/InputSystem/KeyAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @KeyAction: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @KeyAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""KeyAction"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""630a9ffa-e8ca-458c-88e0-8ac144a57b0c"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""f292cfb3-1f1c-41f3-81a6-31f322ec0f14"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""939b673e-c439-48dd-9776-269671660369"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""bfc75f8d-2930-4491-9982-661203512ab2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""39f00996-fab8-4c90-abfb-6d334a234475"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""c2c7e16c-4ac9-4f09-9c57-e0d569986fa5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SkillA"",
                    ""type"": ""Button"",
                    ""id"": ""f2abbb22-1159-4380-b882-6fe12cf1a4f0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SkillS"",
                    ""type"": ""Button"",
                    ""id"": ""44e6bb80-0429-4336-bd8e-f834df313c4d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SkillD"",
                    ""type"": ""Button"",
                    ""id"": ""6637620d-f21c-43c6-9814-ef028a2160bc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SkillF"",
                    ""type"": ""Button"",
                    ""id"": ""35e4f6a1-853f-4859-9838-14537f58a8a7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Keybord"",
                    ""id"": ""0e4fb738-46aa-46d6-9d68-0dcd3230da6c"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""0fde9f99-6e2f-48b7-a0c8-a25dec66d89f"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""9c56d62b-28dc-4861-b1af-f662403b7540"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""196c63bb-f725-430e-931e-5dc29577a623"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.6)"",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""fe79ff7e-44bf-4753-a3d7-48ed18926e03"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""7d64da02-fe0e-49f4-b878-7f2b2d75a4e7"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d3a2d184-1031-4452-8287-097664e6803d"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""805877bd-58a3-4bf6-b977-e518c1b55d3e"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5c93d7f4-d923-4372-b316-838153c195bc"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41b8ec56-b051-4822-a15f-9893e8af85b8"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b9010a24-6ee4-4bf7-ad3c-13b2f03caefd"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c14ab3fd-54fa-440f-98eb-ddc752dc5c91"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a75a4132-5607-4034-a2ce-2a7d2210c89d"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7b93e6b6-bb63-4f94-97d9-f1da987b5d1e"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""036e5470-3994-4d34-a73c-0f3c30b6f3c1"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7b4509a4-9abe-4259-825a-362d8d185cf5"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cbb2fd1c-9aa1-49b3-af28-ba586a9a4ac2"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillS"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a6d636cb-857f-453c-99eb-90f0ae34d48f"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillS"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2686d027-d87c-4d23-b231-77334bf6ef25"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillD"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""23da81ff-c7b8-4464-9eeb-8d3718d5bb16"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillD"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5081be16-d6c6-4251-96db-e589d44e9d1d"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillF"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c7bec353-b6a7-4831-bb03-b44d673c0d8b"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillF"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""7c4da015-8664-403c-94cd-488cd4274933"",
            ""actions"": [
                {
                    ""name"": ""OpenInventory"",
                    ""type"": ""Button"",
                    ""id"": ""644f883a-4ce1-4777-a429-01b30d30d82b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UPInventory"",
                    ""type"": ""Button"",
                    ""id"": ""5309bf4e-34d5-4d95-b5e7-3bc92e50b4c7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DownInventory"",
                    ""type"": ""Button"",
                    ""id"": ""45ec143c-b984-4814-bfda-610adfd2369e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftInventory"",
                    ""type"": ""Button"",
                    ""id"": ""588c9ce1-ec2a-4857-9aaa-993f011fbf58"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightInventory"",
                    ""type"": ""Button"",
                    ""id"": ""2a7eff0c-0048-482f-acf9-4a610227e3c8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""verticalCheck"",
                    ""type"": ""Value"",
                    ""id"": ""44d21c14-01c1-4771-929b-c8b1051d78a2"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""horizontalCheck"",
                    ""type"": ""Value"",
                    ""id"": ""4e716015-77e9-4a9b-9bb6-12bdec7c1da6"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""4ee225da-def7-4a20-ab1b-aa0ef2404e38"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Change"",
                    ""type"": ""Button"",
                    ""id"": ""7e45b8f0-674f-4b80-876a-09c65b7592cf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Divide"",
                    ""type"": ""Button"",
                    ""id"": ""dd68de8b-3e30-4b92-aa48-bd43708d31bc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""8aa8d668-c009-4333-86b9-47ee138b9033"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Enter"",
                    ""type"": ""Button"",
                    ""id"": ""5f3ccbc3-40f7-4f4e-bb52-e93147bfd552"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Up"",
                    ""type"": ""Button"",
                    ""id"": ""9d8b6ec5-17e0-46de-8469-d3762383652a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChestMoveActive"",
                    ""type"": ""Button"",
                    ""id"": ""4c477eaa-85bc-4c1d-92e1-de80c6250dd7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActiveConsum"",
                    ""type"": ""Button"",
                    ""id"": ""757a62aa-feae-4b4c-a0d6-d7c3f15e8e4a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NextRightPage"",
                    ""type"": ""Button"",
                    ""id"": ""9f3a8217-eede-4ff5-88e3-bec9e7af9d1b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NextLeftPage"",
                    ""type"": ""Button"",
                    ""id"": ""a9b7cb42-de0d-409b-9d14-dd7d54c3c7f5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenCraft"",
                    ""type"": ""Button"",
                    ""id"": ""f01700c6-0b83-472e-8611-04f3484ad8d1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d160c9d1-2f7a-45d1-87c1-41464949cb5d"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5baaf8e8-7f44-4016-ba6e-d9a0379473e5"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00d0ffe3-230d-472e-bad3-c39ecb91c556"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UPInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""113b517e-16f4-474e-9460-89a82d33790c"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UPInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""13006dab-cc94-46f1-b517-33bcfd111f99"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.7)"",
                    ""groups"": """",
                    ""action"": ""UPInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8891686f-57b5-404c-ace1-870079a3ae48"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DownInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""56d36b9b-11c6-4071-969b-82e74afd4bc6"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DownInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d95e4f95-80e7-421f-b66a-56e884b6d5f3"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.6)"",
                    ""groups"": """",
                    ""action"": ""DownInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""446be999-bcca-4e24-acf7-5a3fed2dd8d1"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c76042ce-e7db-4142-bc0e-e9dd60efe53b"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""07ea28c9-feef-4367-9259-f4532b1b5740"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.7)"",
                    ""groups"": """",
                    ""action"": ""LeftInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b23eacdc-fb1c-4b89-aaf4-028f6f918c04"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d339664e-7720-4ce7-a4c7-a2b6dc5f8e0f"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f13d2e1-d9ed-4285-acd2-20f3be9402d0"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.7)"",
                    ""groups"": """",
                    ""action"": ""RightInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""bb3f9c48-327e-473a-99af-66e85f12d517"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.6)"",
                    ""groups"": """",
                    ""action"": ""verticalCheck"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""7fcb45dc-02b9-46da-877b-6119bf2b675d"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""verticalCheck"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""5eebd86e-4462-43ec-b9d7-a0a0fe154110"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""verticalCheck"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""49993a4d-ada8-4b32-885b-d258a7256e37"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""verticalCheck"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""c3ed2c5b-e5c6-4655-bd47-e6644ede7513"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""verticalCheck"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""b8054b95-16b8-4884-819c-14fffc1d0551"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""verticalCheck"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""3bd8756b-b8a6-4b12-8a56-b1bbd0c58590"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""verticalCheck"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""6fcf868d-39f9-4bd4-8159-5d506f07a0d1"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""verticalCheck"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""78629529-709e-4fe3-abba-5cc8d4110e38"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""verticalCheck"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""a4d85af1-c24b-460b-910d-43ccc42d55fb"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.6)"",
                    ""groups"": """",
                    ""action"": ""horizontalCheck"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""13ff9cfb-da38-4cbc-8683-a3a2e2919cbe"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""horizontalCheck"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""addaf443-34e5-4f1d-9c34-339dd391b9fb"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""horizontalCheck"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""1cb86d83-5b8c-4134-8f1f-8a384d24a059"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""horizontalCheck"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""196803fb-285a-497f-a2ab-0e1693ed4148"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""horizontalCheck"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""951b7aef-f73f-446c-9334-18ff9ee9fa59"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""horizontalCheck"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""c8b0ccbe-ec8c-4836-952c-9a3039050a2f"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""horizontalCheck"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""7cc4c464-7249-47e0-88e1-00eabe28a600"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""horizontalCheck"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""007b7424-39ec-459e-80bc-e550d759c955"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""horizontalCheck"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f31f5d52-43b9-475c-81a0-c2becae260ba"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3331ffa1-67ae-4add-b6a4-8a0ab33171b7"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5524981b-443d-4d0c-8470-24434d2aa31c"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Change"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e51ee25-57d0-4640-b80f-3e22be109930"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Change"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba225a79-1878-4e1b-8c10-3356450dcace"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Divide"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86638bc1-c1e1-46c3-b0d3-59bb80a7a8dd"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Divide"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3232731-59b6-4e83-81f2-01f5cc175b48"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b280b686-aa1b-4a16-9417-3a4f3d548f98"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6100fc9f-da7d-4e97-a065-a2bb65ddba2f"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Enter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2650ef0f-c1fa-47a2-b171-084066d2c80f"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Enter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b32d3831-0eba-4558-8c54-f940179b8946"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25110917-58c3-469b-b1db-af5e41f970ba"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""23010175-c503-49b3-ad2d-f3ae0f572706"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChestMoveActive"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bbe3d276-9818-458f-bd2d-02318844f156"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChestMoveActive"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15be1296-bf44-43be-9868-a51a9c97d934"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActiveConsum"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9de3ccbc-47c4-491f-9686-51754ef1eecc"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextRightPage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e43dc81-9ed7-44c8-a27d-4ffff4d0185e"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextRightPage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c1efe0b-1aa9-4fab-b050-f9aaed418eb5"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextLeftPage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""43797473-e0b1-458d-a63f-6bf8d11a51d1"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextLeftPage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7b9624b4-a088-40f3-beaf-eeef0ecef151"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenCraft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9667bc21-2ad3-44cb-b7d6-5568699664a1"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenCraft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Portal"",
            ""id"": ""32ccc16e-191e-4b59-b8e3-5caac5557883"",
            ""actions"": [
                {
                    ""name"": ""PortalOn"",
                    ""type"": ""Button"",
                    ""id"": ""f4a1a1e7-8252-40bf-9078-ff40b4ecc735"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""130230b9-9675-4682-b9bc-f8594cd4d3e2"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PortalOn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_Dash = m_Player.FindAction("Dash", throwIfNotFound: true);
        m_Player_Run = m_Player.FindAction("Run", throwIfNotFound: true);
        m_Player_Attack = m_Player.FindAction("Attack", throwIfNotFound: true);
        m_Player_SkillA = m_Player.FindAction("SkillA", throwIfNotFound: true);
        m_Player_SkillS = m_Player.FindAction("SkillS", throwIfNotFound: true);
        m_Player_SkillD = m_Player.FindAction("SkillD", throwIfNotFound: true);
        m_Player_SkillF = m_Player.FindAction("SkillF", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_OpenInventory = m_UI.FindAction("OpenInventory", throwIfNotFound: true);
        m_UI_UPInventory = m_UI.FindAction("UPInventory", throwIfNotFound: true);
        m_UI_DownInventory = m_UI.FindAction("DownInventory", throwIfNotFound: true);
        m_UI_LeftInventory = m_UI.FindAction("LeftInventory", throwIfNotFound: true);
        m_UI_RightInventory = m_UI.FindAction("RightInventory", throwIfNotFound: true);
        m_UI_verticalCheck = m_UI.FindAction("verticalCheck", throwIfNotFound: true);
        m_UI_horizontalCheck = m_UI.FindAction("horizontalCheck", throwIfNotFound: true);
        m_UI_Select = m_UI.FindAction("Select", throwIfNotFound: true);
        m_UI_Change = m_UI.FindAction("Change", throwIfNotFound: true);
        m_UI_Divide = m_UI.FindAction("Divide", throwIfNotFound: true);
        m_UI_Back = m_UI.FindAction("Back", throwIfNotFound: true);
        m_UI_Enter = m_UI.FindAction("Enter", throwIfNotFound: true);
        m_UI_Up = m_UI.FindAction("Up", throwIfNotFound: true);
        m_UI_ChestMoveActive = m_UI.FindAction("ChestMoveActive", throwIfNotFound: true);
        m_UI_ActiveConsum = m_UI.FindAction("ActiveConsum", throwIfNotFound: true);
        m_UI_NextRightPage = m_UI.FindAction("NextRightPage", throwIfNotFound: true);
        m_UI_NextLeftPage = m_UI.FindAction("NextLeftPage", throwIfNotFound: true);
        m_UI_OpenCraft = m_UI.FindAction("OpenCraft", throwIfNotFound: true);
        // Portal
        m_Portal = asset.FindActionMap("Portal", throwIfNotFound: true);
        m_Portal_PortalOn = m_Portal.FindAction("PortalOn", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_Dash;
    private readonly InputAction m_Player_Run;
    private readonly InputAction m_Player_Attack;
    private readonly InputAction m_Player_SkillA;
    private readonly InputAction m_Player_SkillS;
    private readonly InputAction m_Player_SkillD;
    private readonly InputAction m_Player_SkillF;
    public struct PlayerActions
    {
        private @KeyAction m_Wrapper;
        public PlayerActions(@KeyAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @Dash => m_Wrapper.m_Player_Dash;
        public InputAction @Run => m_Wrapper.m_Player_Run;
        public InputAction @Attack => m_Wrapper.m_Player_Attack;
        public InputAction @SkillA => m_Wrapper.m_Player_SkillA;
        public InputAction @SkillS => m_Wrapper.m_Player_SkillS;
        public InputAction @SkillD => m_Wrapper.m_Player_SkillD;
        public InputAction @SkillF => m_Wrapper.m_Player_SkillF;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Dash.started += instance.OnDash;
            @Dash.performed += instance.OnDash;
            @Dash.canceled += instance.OnDash;
            @Run.started += instance.OnRun;
            @Run.performed += instance.OnRun;
            @Run.canceled += instance.OnRun;
            @Attack.started += instance.OnAttack;
            @Attack.performed += instance.OnAttack;
            @Attack.canceled += instance.OnAttack;
            @SkillA.started += instance.OnSkillA;
            @SkillA.performed += instance.OnSkillA;
            @SkillA.canceled += instance.OnSkillA;
            @SkillS.started += instance.OnSkillS;
            @SkillS.performed += instance.OnSkillS;
            @SkillS.canceled += instance.OnSkillS;
            @SkillD.started += instance.OnSkillD;
            @SkillD.performed += instance.OnSkillD;
            @SkillD.canceled += instance.OnSkillD;
            @SkillF.started += instance.OnSkillF;
            @SkillF.performed += instance.OnSkillF;
            @SkillF.canceled += instance.OnSkillF;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Dash.started -= instance.OnDash;
            @Dash.performed -= instance.OnDash;
            @Dash.canceled -= instance.OnDash;
            @Run.started -= instance.OnRun;
            @Run.performed -= instance.OnRun;
            @Run.canceled -= instance.OnRun;
            @Attack.started -= instance.OnAttack;
            @Attack.performed -= instance.OnAttack;
            @Attack.canceled -= instance.OnAttack;
            @SkillA.started -= instance.OnSkillA;
            @SkillA.performed -= instance.OnSkillA;
            @SkillA.canceled -= instance.OnSkillA;
            @SkillS.started -= instance.OnSkillS;
            @SkillS.performed -= instance.OnSkillS;
            @SkillS.canceled -= instance.OnSkillS;
            @SkillD.started -= instance.OnSkillD;
            @SkillD.performed -= instance.OnSkillD;
            @SkillD.canceled -= instance.OnSkillD;
            @SkillF.started -= instance.OnSkillF;
            @SkillF.performed -= instance.OnSkillF;
            @SkillF.canceled -= instance.OnSkillF;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private List<IUIActions> m_UIActionsCallbackInterfaces = new List<IUIActions>();
    private readonly InputAction m_UI_OpenInventory;
    private readonly InputAction m_UI_UPInventory;
    private readonly InputAction m_UI_DownInventory;
    private readonly InputAction m_UI_LeftInventory;
    private readonly InputAction m_UI_RightInventory;
    private readonly InputAction m_UI_verticalCheck;
    private readonly InputAction m_UI_horizontalCheck;
    private readonly InputAction m_UI_Select;
    private readonly InputAction m_UI_Change;
    private readonly InputAction m_UI_Divide;
    private readonly InputAction m_UI_Back;
    private readonly InputAction m_UI_Enter;
    private readonly InputAction m_UI_Up;
    private readonly InputAction m_UI_ChestMoveActive;
    private readonly InputAction m_UI_ActiveConsum;
    private readonly InputAction m_UI_NextRightPage;
    private readonly InputAction m_UI_NextLeftPage;
    private readonly InputAction m_UI_OpenCraft;
    public struct UIActions
    {
        private @KeyAction m_Wrapper;
        public UIActions(@KeyAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @OpenInventory => m_Wrapper.m_UI_OpenInventory;
        public InputAction @UPInventory => m_Wrapper.m_UI_UPInventory;
        public InputAction @DownInventory => m_Wrapper.m_UI_DownInventory;
        public InputAction @LeftInventory => m_Wrapper.m_UI_LeftInventory;
        public InputAction @RightInventory => m_Wrapper.m_UI_RightInventory;
        public InputAction @verticalCheck => m_Wrapper.m_UI_verticalCheck;
        public InputAction @horizontalCheck => m_Wrapper.m_UI_horizontalCheck;
        public InputAction @Select => m_Wrapper.m_UI_Select;
        public InputAction @Change => m_Wrapper.m_UI_Change;
        public InputAction @Divide => m_Wrapper.m_UI_Divide;
        public InputAction @Back => m_Wrapper.m_UI_Back;
        public InputAction @Enter => m_Wrapper.m_UI_Enter;
        public InputAction @Up => m_Wrapper.m_UI_Up;
        public InputAction @ChestMoveActive => m_Wrapper.m_UI_ChestMoveActive;
        public InputAction @ActiveConsum => m_Wrapper.m_UI_ActiveConsum;
        public InputAction @NextRightPage => m_Wrapper.m_UI_NextRightPage;
        public InputAction @NextLeftPage => m_Wrapper.m_UI_NextLeftPage;
        public InputAction @OpenCraft => m_Wrapper.m_UI_OpenCraft;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void AddCallbacks(IUIActions instance)
        {
            if (instance == null || m_Wrapper.m_UIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIActionsCallbackInterfaces.Add(instance);
            @OpenInventory.started += instance.OnOpenInventory;
            @OpenInventory.performed += instance.OnOpenInventory;
            @OpenInventory.canceled += instance.OnOpenInventory;
            @UPInventory.started += instance.OnUPInventory;
            @UPInventory.performed += instance.OnUPInventory;
            @UPInventory.canceled += instance.OnUPInventory;
            @DownInventory.started += instance.OnDownInventory;
            @DownInventory.performed += instance.OnDownInventory;
            @DownInventory.canceled += instance.OnDownInventory;
            @LeftInventory.started += instance.OnLeftInventory;
            @LeftInventory.performed += instance.OnLeftInventory;
            @LeftInventory.canceled += instance.OnLeftInventory;
            @RightInventory.started += instance.OnRightInventory;
            @RightInventory.performed += instance.OnRightInventory;
            @RightInventory.canceled += instance.OnRightInventory;
            @verticalCheck.started += instance.OnVerticalCheck;
            @verticalCheck.performed += instance.OnVerticalCheck;
            @verticalCheck.canceled += instance.OnVerticalCheck;
            @horizontalCheck.started += instance.OnHorizontalCheck;
            @horizontalCheck.performed += instance.OnHorizontalCheck;
            @horizontalCheck.canceled += instance.OnHorizontalCheck;
            @Select.started += instance.OnSelect;
            @Select.performed += instance.OnSelect;
            @Select.canceled += instance.OnSelect;
            @Change.started += instance.OnChange;
            @Change.performed += instance.OnChange;
            @Change.canceled += instance.OnChange;
            @Divide.started += instance.OnDivide;
            @Divide.performed += instance.OnDivide;
            @Divide.canceled += instance.OnDivide;
            @Back.started += instance.OnBack;
            @Back.performed += instance.OnBack;
            @Back.canceled += instance.OnBack;
            @Enter.started += instance.OnEnter;
            @Enter.performed += instance.OnEnter;
            @Enter.canceled += instance.OnEnter;
            @Up.started += instance.OnUp;
            @Up.performed += instance.OnUp;
            @Up.canceled += instance.OnUp;
            @ChestMoveActive.started += instance.OnChestMoveActive;
            @ChestMoveActive.performed += instance.OnChestMoveActive;
            @ChestMoveActive.canceled += instance.OnChestMoveActive;
            @ActiveConsum.started += instance.OnActiveConsum;
            @ActiveConsum.performed += instance.OnActiveConsum;
            @ActiveConsum.canceled += instance.OnActiveConsum;
            @NextRightPage.started += instance.OnNextRightPage;
            @NextRightPage.performed += instance.OnNextRightPage;
            @NextRightPage.canceled += instance.OnNextRightPage;
            @NextLeftPage.started += instance.OnNextLeftPage;
            @NextLeftPage.performed += instance.OnNextLeftPage;
            @NextLeftPage.canceled += instance.OnNextLeftPage;
            @OpenCraft.started += instance.OnOpenCraft;
            @OpenCraft.performed += instance.OnOpenCraft;
            @OpenCraft.canceled += instance.OnOpenCraft;
        }

        private void UnregisterCallbacks(IUIActions instance)
        {
            @OpenInventory.started -= instance.OnOpenInventory;
            @OpenInventory.performed -= instance.OnOpenInventory;
            @OpenInventory.canceled -= instance.OnOpenInventory;
            @UPInventory.started -= instance.OnUPInventory;
            @UPInventory.performed -= instance.OnUPInventory;
            @UPInventory.canceled -= instance.OnUPInventory;
            @DownInventory.started -= instance.OnDownInventory;
            @DownInventory.performed -= instance.OnDownInventory;
            @DownInventory.canceled -= instance.OnDownInventory;
            @LeftInventory.started -= instance.OnLeftInventory;
            @LeftInventory.performed -= instance.OnLeftInventory;
            @LeftInventory.canceled -= instance.OnLeftInventory;
            @RightInventory.started -= instance.OnRightInventory;
            @RightInventory.performed -= instance.OnRightInventory;
            @RightInventory.canceled -= instance.OnRightInventory;
            @verticalCheck.started -= instance.OnVerticalCheck;
            @verticalCheck.performed -= instance.OnVerticalCheck;
            @verticalCheck.canceled -= instance.OnVerticalCheck;
            @horizontalCheck.started -= instance.OnHorizontalCheck;
            @horizontalCheck.performed -= instance.OnHorizontalCheck;
            @horizontalCheck.canceled -= instance.OnHorizontalCheck;
            @Select.started -= instance.OnSelect;
            @Select.performed -= instance.OnSelect;
            @Select.canceled -= instance.OnSelect;
            @Change.started -= instance.OnChange;
            @Change.performed -= instance.OnChange;
            @Change.canceled -= instance.OnChange;
            @Divide.started -= instance.OnDivide;
            @Divide.performed -= instance.OnDivide;
            @Divide.canceled -= instance.OnDivide;
            @Back.started -= instance.OnBack;
            @Back.performed -= instance.OnBack;
            @Back.canceled -= instance.OnBack;
            @Enter.started -= instance.OnEnter;
            @Enter.performed -= instance.OnEnter;
            @Enter.canceled -= instance.OnEnter;
            @Up.started -= instance.OnUp;
            @Up.performed -= instance.OnUp;
            @Up.canceled -= instance.OnUp;
            @ChestMoveActive.started -= instance.OnChestMoveActive;
            @ChestMoveActive.performed -= instance.OnChestMoveActive;
            @ChestMoveActive.canceled -= instance.OnChestMoveActive;
            @ActiveConsum.started -= instance.OnActiveConsum;
            @ActiveConsum.performed -= instance.OnActiveConsum;
            @ActiveConsum.canceled -= instance.OnActiveConsum;
            @NextRightPage.started -= instance.OnNextRightPage;
            @NextRightPage.performed -= instance.OnNextRightPage;
            @NextRightPage.canceled -= instance.OnNextRightPage;
            @NextLeftPage.started -= instance.OnNextLeftPage;
            @NextLeftPage.performed -= instance.OnNextLeftPage;
            @NextLeftPage.canceled -= instance.OnNextLeftPage;
            @OpenCraft.started -= instance.OnOpenCraft;
            @OpenCraft.performed -= instance.OnOpenCraft;
            @OpenCraft.canceled -= instance.OnOpenCraft;
        }

        public void RemoveCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUIActions instance)
        {
            foreach (var item in m_Wrapper.m_UIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UIActions @UI => new UIActions(this);

    // Portal
    private readonly InputActionMap m_Portal;
    private List<IPortalActions> m_PortalActionsCallbackInterfaces = new List<IPortalActions>();
    private readonly InputAction m_Portal_PortalOn;
    public struct PortalActions
    {
        private @KeyAction m_Wrapper;
        public PortalActions(@KeyAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @PortalOn => m_Wrapper.m_Portal_PortalOn;
        public InputActionMap Get() { return m_Wrapper.m_Portal; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PortalActions set) { return set.Get(); }
        public void AddCallbacks(IPortalActions instance)
        {
            if (instance == null || m_Wrapper.m_PortalActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PortalActionsCallbackInterfaces.Add(instance);
            @PortalOn.started += instance.OnPortalOn;
            @PortalOn.performed += instance.OnPortalOn;
            @PortalOn.canceled += instance.OnPortalOn;
        }

        private void UnregisterCallbacks(IPortalActions instance)
        {
            @PortalOn.started -= instance.OnPortalOn;
            @PortalOn.performed -= instance.OnPortalOn;
            @PortalOn.canceled -= instance.OnPortalOn;
        }

        public void RemoveCallbacks(IPortalActions instance)
        {
            if (m_Wrapper.m_PortalActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPortalActions instance)
        {
            foreach (var item in m_Wrapper.m_PortalActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PortalActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PortalActions @Portal => new PortalActions(this);
    public interface IPlayerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnSkillA(InputAction.CallbackContext context);
        void OnSkillS(InputAction.CallbackContext context);
        void OnSkillD(InputAction.CallbackContext context);
        void OnSkillF(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnOpenInventory(InputAction.CallbackContext context);
        void OnUPInventory(InputAction.CallbackContext context);
        void OnDownInventory(InputAction.CallbackContext context);
        void OnLeftInventory(InputAction.CallbackContext context);
        void OnRightInventory(InputAction.CallbackContext context);
        void OnVerticalCheck(InputAction.CallbackContext context);
        void OnHorizontalCheck(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
        void OnChange(InputAction.CallbackContext context);
        void OnDivide(InputAction.CallbackContext context);
        void OnBack(InputAction.CallbackContext context);
        void OnEnter(InputAction.CallbackContext context);
        void OnUp(InputAction.CallbackContext context);
        void OnChestMoveActive(InputAction.CallbackContext context);
        void OnActiveConsum(InputAction.CallbackContext context);
        void OnNextRightPage(InputAction.CallbackContext context);
        void OnNextLeftPage(InputAction.CallbackContext context);
        void OnOpenCraft(InputAction.CallbackContext context);
    }
    public interface IPortalActions
    {
        void OnPortalOn(InputAction.CallbackContext context);
    }
}
